apiVersion: apps/v1
kind: Deployment
metadata:
  name: r3det-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      hostIPC: true
      containers:
      - name: r3det-container
        image: minibeast-ubuntu16:443/r3det:latest
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: 20Gi
          limits:
            nvidia.com/gpu: 1
            memory: 60Gi
        volumeMounts:
          - name: nfs
            mountPath: "/data/dota"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      priorityClassName: high-priority
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cluster
                operator: In
                values:
                - '001'
                - '002'
                - '003'
                - '004'
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: pvc-nfs-dota
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001