apiVersion: apps/v1
kind: Deployment
metadata:
  name: odtk-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      hostIPC: true
      containers:
      - name: odtk-container
        image: minibeast-ubuntu16:443/odtk:latest
        resources:
          limits:
            nvidia.com/gpu: 6
        volumeMounts:
          - name: nfs
            mountPath: "/coco"
        command: ["/bin/sh"]
        args: ["-c", "odtk train /coco/models/test.pth --backbone ResNet50FPN --batch 6 --images /coco/images/train2017/ --annotations /coco/annotations/instances_train2017.json --val-images /coco/images/val2017/ --val-annotations /coco/annotations/instances_val2017.json &> /coco/logs/test.log"]
      priorityClassName: high-priority
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cluster
                operator: In
                values:
                - '001'
                - '002'
                - '003'
                - '004'
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: pvc-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001