apiVersion: apps/v1
kind: Deployment
metadata:
  name: odtk-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: odtk-container
        image: minibeast-ubuntu16:443/odtk:latest
        volumeMounts:
          - name: smb
            mountPath: "/datasets/smb"
        command: ["/bin/sh"]
        args: ["-c", "echo Testing from cam > /datasets/smb/pub/coco/logs/out.txt"]
      priorityClassName: high-priority
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cluster
                operator: In
                values:
                - '001'
                - '002'
                - '003'
                - '004'
  volumeClaimTemplates:
    - metadata:
        name: smb
        annotations:
          volume.beta.kubernetes.io/storage-class: smb
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001