apiVersion: apps/v1
kind: Deployment
metadata:
  name: odtk-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      volumes:
      - name: coco-data
        hostPath: /mnt/md0/share/pub/coco
      containers:
      - name: odtk-container
        image: minibeast-ubuntu16:443/odtk:latest
        volumeMounts:
          - name: coco-data
            mountPath: /coco
        command: ["/bin/sh"]
        args: ["-c", "echo Hello from the debian container > /coco/logs/out.txt"]
      priorityClassName: high-priority
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cluster
                operator: In
                values:
                - '001'
                - '002'
                - '003'
                - '004'
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001