apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.188.43
    path: "/mnt/md0/cocoshare"